# Java / Gradle Settings
java_version=21
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

# Minecraft / Loader Settings
minecraft_version=1.21.1
neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21.1
parchment_version=2024.11.17
neoforge_minecraft_version_range=[1.21, 26)
fabric_minecraft_version_range=>=1.21 <26
fabric_version=0.109.0+1.21.1
fabric_loader_version=0.16.9
neoforge_version=21.1.80
neoforge_loader_version_range=[4,)

# Mod Details
mod_author=Jason13
mod_id=specter
mod_name=Specter
version=1.1.2
license=Unlicense
group=io.github.jason13official.specter
mod_url=https://github.com/jason13official/Specter-Mod
credits=Thanks to Kaupenjoe, Jaredlll08, Darkhax, Serilum, and PacifistMC.
description=Inspired by Ghosts from Destiny (2014).
