# Java / Gradle Settings
java_version=17
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

# Minecraft / Loader Settings
minecraft_version=1.20.1
parchment_minecraft=1.20.1
parchment_version=2023.09.03
forge_minecraft_version_range=[1.20, 1.21)
fabric_minecraft_version_range=>=1.20 <1.21
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9
forge_version=47.2.30
forge_loader_version_range=[47,)

# Mod Details
mod_author=Jason13
mod_id=specter
mod_name=Specter
version=1.2.0
license=Unlicense
group=io.github.jason13official.specter
mod_url=https://github.com/jason13official/Specter-Mod
credits=Thanks to Kaupenjoe, Jaredlll08, Darkhax, Serilum, and PacifistMC.
description=Inspired by Ghosts from Destiny (2014).
